### ISSUE TITLE
Ignore Field

### ISSUE THREAD

**Issue by johnrichardrinehart** [plaid/go-envvar#16]
Is there a directive that can be included in the tag to have `Parse` ignore a field. This would be really useful, especially when `Parse`-ing into a `struct` which contains fields with hidden members for which `go-envvar`/`envvar` would not have been used anyway.

**Comment by ntindall** [comment]
@johnrichardrinehart good call out. @jeeyoungk what do you think about adding `envvar:"-"` as a way to facilitate this behavior? 

I don't think we have hit this use case internally, since we usually have dedicated structs for parsing the env configuration.

**Comment by johnrichardrinehart** [comment]
@ntindall This seems low priority and I'm happy to flex my `go` fingers a bit. I'll try to find some time in the coming days to issue a PR using a fork since my feature suggestion hasn't been rejected as unreasonable.

**Comment by ntindall** [comment]
definitely not unreasonable 🙂 - looking forward!
