### ISSUE TITLE
Display all required environment variables

### ISSUE THREAD

**Issue by albrow** [plaid/go-envvar#7]
See plaid/style#37 for a background.

There is also a corresponding issue on the node envvar library at https://github.com/plaid/envvar/issues/2.

I believe there are two things we should do to make environment variables more pleasant to work with.
1. We should add a `--help` flag to all service executables which prints out the required environment variables, and optionally some other information about the service.
2. When you forget a required env var, _all_ required env vars should be printed out, not just the one you forgot. This will reduce time to get up and running and eliminate the cycle of add the env var, run the service, add another env var, run it again, etc. It might make sense to just print the help text in this case.

**Comment by ntindall** [comment]
Fixed by #8
